"""Response playbooks (NIST SP 800-61r2 phase model) used by the
Recommendation agent and rendered as the interactive checklist in the UI."""

from __future__ import annotations

PHASES = ["identification", "containment", "eradication", "recovery", "lessons-learned"]

PLAYBOOKS: dict[str, dict] = {
    "pb-bruteforce": {
        "name": "Credential Brute Force Response",
        "applies_to": ["brute-force", "credential-access"],
        "sla_minutes": 60,
        "steps": [
            ("identification", "Confirm the failure burst is not a misconfigured service account",
             "Check whether the source IP maps to a known automation host or CI runner before treating it as hostile.", False),
            ("containment", "Block the source IP at the perimeter firewall",
             "Push a deny rule for the offending source; note the rule ID in the case for rollback.", True),
            ("containment", "Force password reset for every targeted account",
             "Reset all accounts that appeared in the failure stream, prioritising any that later succeeded.", True),
            ("containment", "Revoke active sessions and refresh tokens",
             "Invalidate sessions so a captured credential cannot be replayed after the reset.", True),
            ("eradication", "Verify no successful authentication followed the burst",
             "Query the auth log for the same source and usernames over the full attack window plus 24h.", False),
            ("eradication", "Disable password authentication on the exposed service",
             "For SSH, set PasswordAuthentication no and move to certificate-based access.", False),
            ("recovery", "Re-enable access for confirmed-legitimate users",
             "Restore normal access after reset, with MFA enrolment verified.", False),
            ("recovery", "Enable rate limiting and lockout thresholds",
             "Apply fail2ban or equivalent so repeat attempts are throttled automatically.", True),
            ("lessons-learned", "Record IOCs and update the detection rule",
             "Add the source range to the watchlist and tune the threshold if this was a false positive.", False),
        ],
    },
    "pb-webexploit": {
        "name": "Web Application Exploitation Response",
        "applies_to": ["web-exploit", "intrusion-attempt"],
        "sla_minutes": 30,
        "steps": [
            ("identification", "Reproduce the request and confirm exploitability",
             "Replay the payload against a staging copy — never production — to establish real impact.", False),
            ("identification", "Determine whether the response indicates success",
             "A 200 with unusual body size after a 500 series is the strongest success signal.", False),
            ("containment", "Deploy a WAF virtual patch for the payload signature",
             "Block the specific pattern while the code fix is developed.", True),
            ("containment", "Isolate the affected web node from the data tier",
             "Restrict the node's DB credentials to read-only or cut the path entirely.", True),
            ("eradication", "Scan the web root for dropped web shells",
             "File-integrity comparison against the last known-good deployment artifact.", True),
            ("eradication", "Patch the vulnerable component and redeploy",
             "Ship the dependency upgrade or code fix through the normal release pipeline.", False),
            ("recovery", "Rebuild the node from a trusted image",
             "Never clean in place after confirmed RCE — replace the instance.", False),
            ("recovery", "Restore full connectivity and monitor for 48h",
             "Watch for re-exploitation attempts from related infrastructure.", False),
            ("lessons-learned", "Add a regression test for the payload",
             "Encode the exploit as a test so the fix cannot silently regress.", False),
        ],
    },
    "pb-exfiltration": {
        "name": "Data Exfiltration Response",
        "applies_to": ["data-exfiltration"],
        "sla_minutes": 20,
        "steps": [
            ("identification", "Quantify the volume and classify the data moved",
             "Establish bytes transferred and whether the source store holds regulated data.", False),
            ("identification", "Identify the destination and its reputation",
             "Resolve the destination and run a reputation lookup before blocking upstream.", True),
            ("containment", "Block egress to the destination at the proxy",
             "Apply the block broadly enough to cover related infrastructure, not just one IP.", True),
            ("containment", "Suspend the implicated account and rotate its credentials",
             "Includes API keys and service tokens held by the account.", True),
            ("eradication", "Remove the collection tooling and staging archives",
             "Locate and delete staged archives; preserve copies as evidence first.", False),
            ("recovery", "Assess regulatory notification obligations",
             "GDPR Art. 33 is a 72-hour clock from awareness — start the assessment immediately.", False),
            ("recovery", "Restore service with DLP enforcement enabled",
             "Ensure the DLP rule that should have caught this is now in blocking mode.", False),
            ("lessons-learned", "Review data-tier access scope",
             "Confirm least privilege on the store involved; remove standing broad access.", False),
        ],
    },
    "pb-ransomware": {
        "name": "Ransomware Precursor / Encryption Response",
        "applies_to": ["ransomware"],
        "sla_minutes": 15,
        "steps": [
            ("identification", "Confirm encryption activity versus benign bulk file change",
             "Check rename entropy and extension changes before declaring a ransomware event.", False),
            ("containment", "Network-isolate affected endpoints immediately",
             "EDR isolation, not shutdown — memory evidence is lost on power-off.", True),
            ("containment", "Disable the compromised account domain-wide",
             "Stop propagation via the account being used for spread.", True),
            ("containment", "Protect and verify backup integrity",
             "Confirm the backup tier is unreachable from the compromised credential set.", True),
            ("eradication", "Identify the strain and the initial entry vector",
             "Ransom note and file markers identify the family; entry vector drives the real fix.", False),
            ("eradication", "Remove persistence across all touched hosts",
             "Scheduled tasks, services, run keys and any planted accounts.", True),
            ("recovery", "Restore from the most recent clean backup",
             "Restore into a clean network segment and validate before reconnecting.", False),
            ("recovery", "Stage service restoration by business criticality",
             "Bring back tier-1 services first, monitoring for reinfection at each stage.", False),
            ("lessons-learned", "Run a formal post-incident review within 5 business days",
             "Document dwell time, detection gaps and the control changes committed to.", False),
        ],
    },
    "pb-privesc": {
        "name": "Privilege Escalation Response",
        "applies_to": ["privilege-escalation"],
        "sla_minutes": 45,
        "steps": [
            ("identification", "Establish the escalation path actually used",
             "Sudo misconfiguration, setuid binary, kernel exploit or token theft — the fix differs per path.", False),
            ("containment", "Terminate elevated sessions on the affected host",
             "Kill the elevated shells and revoke associated tokens.", True),
            ("containment", "Freeze the host's credentials and keys",
             "Rotate host keys and any service credentials resident on the machine.", True),
            ("eradication", "Patch or reconfigure the abused mechanism",
             "Apply the kernel patch or correct the sudoers/setuid misconfiguration.", False),
            ("eradication", "Audit for accounts and keys added while elevated",
             "Diff /etc/passwd, sudoers and authorized_keys against the baseline.", True),
            ("recovery", "Return the host to service under enhanced monitoring",
             "Elevated logging for 7 days post-restore.", False),
            ("lessons-learned", "Extend the check to the whole fleet",
             "The same misconfiguration is rarely unique to one host — sweep and remediate broadly.", False),
        ],
    },
    "pb-lateral": {
        "name": "Lateral Movement Response",
        "applies_to": ["lateral-movement"],
        "sla_minutes": 40,
        "steps": [
            ("identification", "Map the full east-west session graph for the actor",
             "Build the host-to-host path so containment covers every touched node.", True),
            ("containment", "Apply segmentation policy blocking the observed path",
             "Deny the specific east-west flows while the investigation continues.", True),
            ("containment", "Rotate SSH keys and service credentials on the path",
             "Assume every credential resident on a touched host is compromised.", True),
            ("eradication", "Hunt for persistence on every host in the path",
             "Cron, systemd timers, authorized_keys and new local accounts.", False),
            ("recovery", "Restore connectivity host by host with verification",
             "Reconnect only after each host passes the persistence sweep.", False),
            ("lessons-learned", "Codify the connectivity matrix as policy",
             "Turn the expected-flow model into enforced default-deny segmentation.", False),
        ],
    },
    "pb-recon": {
        "name": "Reconnaissance / Scanning Response",
        "applies_to": ["reconnaissance", "availability"],
        "sla_minutes": 240,
        "steps": [
            ("identification", "Confirm scan scope and whether any probe succeeded",
             "Distinguish blanket internet noise from targeted enumeration of your ranges.", False),
            ("containment", "Rate-limit or block the scanning source",
             "Edge throttle first; a full block only if the source is clearly hostile.", True),
            ("eradication", "Close or firewall any unexpectedly exposed service found",
             "The scan output is a free external attack-surface report — act on it.", False),
            ("recovery", "Confirm the exposed surface matches the approved baseline",
             "Reconcile against the asset inventory and approved exposure list.", False),
            ("lessons-learned", "Schedule recurring external surface scanning",
             "Find your own exposure before an adversary maps it for you.", False),
        ],
    },
    "pb-policy": {
        "name": "Policy Violation / Unsanctioned Tooling",
        "applies_to": ["policy-violation", "persistence", "defense-evasion"],
        "sla_minutes": 480,
        "steps": [
            ("identification", "Confirm the tool and the business justification",
             "Speak to the owning team before enforcement — many cases are shadow IT, not malice.", False),
            ("containment", "Block the tool's control domains at DNS",
             "Prevent further sessions while the exception is assessed.", True),
            ("eradication", "Remove the unsanctioned software from affected endpoints",
             "Push removal through endpoint management.", True),
            ("recovery", "Provide the sanctioned equivalent to the requesting team",
             "Enforcement without an alternative just drives the behaviour further underground.", False),
            ("lessons-learned", "Update the acceptable-use policy and the allow-list",
             "Close the ambiguity that permitted the deployment.", False),
        ],
    },
}


def for_category(category: str) -> tuple[str, dict]:
    for key, pb in PLAYBOOKS.items():
        if category in pb["applies_to"]:
            return key, pb
    return "pb-policy", PLAYBOOKS["pb-policy"]


def get(key: str) -> dict | None:
    return PLAYBOOKS.get(key)
